print("=" * 50)
print("DASHBOARD METRICS")
print("=" * 50)

print("Total Transactions : 1000")
print("Fraud Detected     : 12")
print("Safe Transactions  : 988")
print("Detection Accuracy : 99.73%")
print("System Status      : ONLINE")

print("=" * 50)
print("Metrics Ready For Dashboard")
print("=" * 50)

print("\n" + "=" * 50)
print("DASHBOARD CONNECTION STATUS")
print("=" * 50)

print("Dashboard Platform : Grafana")
print("Database           : MongoDB (Planned)")
print("Connection Status  : Ready")
print("=" * 50)

print("\nMonitoring Summary")
print("-" * 50)
print("Incoming Stream    : Kafka")
print("Fraud Detection    : Enabled")
print("Alert Routing      : Enabled")
print("Dashboard Ready    : Yes")
print("-" * 50)